# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'teachAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'SDWebImage', '~> 4.0'
  # Pods for leARn

end
